# Generated by Django 5.1.1 on 2024-10-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyect',
            options={'ordering': ['-created'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyect',
            name='icon',
            field=models.ImageField(blank=True, upload_to='projects', verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='image',
            field=models.ImageField(upload_to='projects', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
