# Generated by Django 5.1.1 on 2024-11-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_proyect_options_proyect_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='urlProyecto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Git'),
        ),
    ]
