# Generated by Django 5.1.1 on 2024-11-05 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
